classdef EarthWorm_OPA < audioPlugin
    properties (Access = public)
        distortionNormalized = 0.5; % Normalized control for distortion parameter, 0:1
        toneNormalized = 0.5; % Normalized control for tone parameter, 0:1
        volumeNormalized = 0.5; % Normalized control for tone parameter, 0:1
        symmetry = 1;
        opaChoice = EarthWorm_OPA_Selection.Rodent;
        bypass = false;
    end

    properties (Access = private)
        worm;
    end

    properties (Constant)
        PluginInterface = audioPluginInterface(...
            audioPluginGridLayout( ...
            'RowHeight',[50,50,20,70,30,20], ...
            'ColumnWidth',[100,100,100],...
            'Padding',[20,20,20,20]),...
            'BackgroundColor','w',...
            'PluginName','EarthWorm OPA',...
            audioPluginParameter('distortionNormalized',...
            'Style','rotaryknob',...
            'Layout',[1,1;2,1],...
            'DisplayName','Distortion','DisplayNameLocation','Below',...
            'Mapping',{'log', 0.1, 1}),...
            audioPluginParameter('toneNormalized',...
            'Style', 'rotaryknob',...
            'Layout',[1,2;2,2],...
            'DisplayName','Tone','DisplayNameLocation','Below',...
            'Mapping',{'lin', 0, 1}),...
            audioPluginParameter('volumeNormalized',...
            'Style','rotaryknob',...
            'Layout',[1,3;2,3],...
            'DisplayName', 'Volume','DisplayNameLocation','Below',...
            'Mapping',{'lin', 0, 1}),...
            audioPluginParameter('symmetry',...
            'Style','rotaryknob',...
            'Layout',[4,1;5,1],...
            'DisplayName','Symmetry','DisplayNameLocation','Below',...
            'Mapping',{'lin', 0, 1}),...
            audioPluginParameter('opaChoice',...
            'Layout',[5,2],...
            'DisplayName','Op Amp Choice','DisplayNameLocation','Below',...
            'Mapping',{'enum','Rodent','Plus','Screamer','Horse'}),...
             audioPluginParameter('bypass', ...
            'Style', 'vtoggle', ...
            'Layout',[4,3;5,3], ...
            'DisplayName','Bypass','DisplayNameLocation','Below'));
    end

    methods
        % Constructor
        function o = EarthWorm_OPA()
            o.worm = EarthWorm_OPA_Effect();
            o.worm.PrepareToPlay(getSampleRate(o));
        end

        % Prepare To Play
        function reset(o)
            Fs = getSampleRate(o);
            o.worm.PrepareToPlay(Fs);
        end

        % DSP
        function out = process(o, in)
            out = o.worm.process(in);
        end

        % Plugin Parameters
        function set.distortionNormalized(o,distortionNormalized)
            o.distortionNormalized = distortionNormalized;
            o.worm.setDistortion(distortionNormalized);
        end

        function set.toneNormalized(o,toneNormalized)
            o.toneNormalized = toneNormalized;
            o.worm.setTone(toneNormalized);
        end

        function set.volumeNormalized(o,volumeNormalized)
            o.volumeNormalized = volumeNormalized;
            o.worm.setVolume(volumeNormalized);
        end

        function set.symmetry(o,symmetry)
            o.symmetry = symmetry;
            o.worm.setSupplyVoltage(symmetry);
        end

        function set.opaChoice(o,opaChoice)
            o.opaChoice = opaChoice;
            switch(o.opaChoice)
                case 1
                    o.worm.selectOPA(1);
                case 2
                    o.worm.selectOPA(2);
                case 3
                    o.worm.selectOPA(3);
                case 4
                    o.worm.selectOPA(4);
            end
        end

        function set.bypass(o,bypass)
            o.bypass = bypass;
            o.worm.setBypass(bypass);
        end
    end
end
